#!/bin/sh
set -e

if [ "$1" = "configure" ]; then
    # Update icon cache
    if which gtk-update-icon-cache >/dev/null 2>&1; then
        gtk-update-icon-cache -q -t -f /usr/share/icons/hicolor || true
    fi
    # Update desktop database
    if which update-desktop-database >/dev/null 2>&1; then
        update-desktop-database -q || true
    fi
fi

exit 0
