"""
MintStatLab - Academic Report & Data Exporter
Exports formatted LaTeX tables/reports, raw CSV telemetry datasets, and JSON schemas.
"""

import json
import csv
from typing import Dict, List, Any


def export_latex_report(filepath: str, snap: Any, moments_ram: Dict[str, float], moments_cpu: Dict[str, float],
                        gini_ram: float, gini_cpu: float, fit_info: Dict[str, Any],
                        km_user: Dict[str, Any], point_res: Dict[str, Any], reg_drift: Dict[str, Any]) -> bool:
    """Generates an academic-grade LaTeX report document with statistical tables and formulas."""
    try:
        ln = fit_info.get("lognormal", {})
        tex = f"""% Auto-generated by MintStatLab (Linux Mint Statistical Telemetry Lab)
\\documentclass[11pt,a4paper]{{article}}
\\usepackage[margin=1in]{{geometry}}
\\usepackage{{amsmath,amssymb}}
\\usepackage{{booktabs}}
\\usepackage{{hyperref}}

\\title{{\\textbf{{Linux Mint System Statistical Telemetry \\& Empirical Modeling Report}}}}
\\author{{MintStatLab Academic Telemetry Engine}}
\\date{{\\today}}

\\begin{{document}}
\\maketitle

\\begin{{abstract}}
This report presents an empirical statistical investigation of Linux Mint operating system resources, modeling process memory allocation via heavy-tail probability distributions, quantifying resource concentration via the Gini coefficient and Lorenz curves, evaluating process survival dynamics through non-parametric Kaplan-Meier estimators, and testing system event inter-arrival times against the homogeneous Poisson Point Process hypothesis.
\\end{{abstract}}

\\section{{Empirical Moments and Inequality Analysis}}
Table~\\ref{{tab:moments}} summarizes sample dispersion metrics and higher-order moments across active processes ($N = {moments_ram.get('n', 0)}$).

\\begin{{table}}[htbp]
\\centering
\\caption{{Statistical Moments of Linux Mint System Resources}}
\\label{{tab:moments}}
\\begin{{tabular}}{{lrr}}
\\toprule
\\textbf{{Metric}} & \\textbf{{RAM Usage (MiB)}} & \\textbf{{CPU Load (\\%)}} \\\\
\\midrule
Sample Mean ($\\bar{{x}}$) & {moments_ram.get('mean', 0.0):.2f} & {moments_cpu.get('mean', 0.0):.2f} \\\\
Median ($\\tilde{{x}}$) & {moments_ram.get('median', 0.0):.2f} & {moments_cpu.get('median', 0.0):.2f} \\\\
Std. Deviation ($s$) & {moments_ram.get('std', 0.0):.2f} & {moments_cpu.get('std', 0.0):.2f} \\\\
Interquartile Range ($IQR$) & {moments_ram.get('iqr', 0.0):.2f} & {moments_cpu.get('iqr', 0.0):.2f} \\\\
Median Absolute Deviation ($MAD$) & {moments_ram.get('mad', 0.0):.2f} & {moments_cpu.get('mad', 0.0):.2f} \\\\
Fisher Skewness ($g_1$) & {moments_ram.get('skewness', 0.0):.2f} & {moments_cpu.get('skewness', 0.0):.2f} \\\\
Excess Kurtosis ($g_2$) & {moments_ram.get('excess_kurtosis', 0.0):.2f} & {moments_cpu.get('excess_kurtosis', 0.0):.2f} \\\\
\\midrule
\\textbf{{Gini Inequality Coefficient ($G$)}} & \\textbf{{{gini_ram:.4f}}} & \\textbf{{{gini_cpu:.4f}}} \\\\
\\bottomrule
\\end{{tabular}}
\\end{{table}}

The Gini coefficient is formulated as:
\\begin{{equation}}
G = \\frac{{\\sum_{{i=1}}^n \\sum_{{j=1}}^n |x_i - x_j|}}{{2n^2 \\bar{{x}}}} = \\frac{{2 \\sum_{{i=1}}^n i x_{{(i)}}}}{{n \\sum_{{i=1}}^n x_{{(i)}}}} - \\frac{{n+1}}{{n}}
\\end{{equation}}

\\section{{Parametric Heavy-Tail Distribution Fitting}}
Process memory footprint exhibits significant right-skewed leptokurtosis ($g_1 = {moments_ram.get('skewness', 0.0):.2f}$, $g_2 = {moments_ram.get('excess_kurtosis', 0.0):.2f}$).
Maximum Likelihood Estimation (MLE) yielded the following parameters:
\\begin{{itemize}}
    \\item \\textbf{{Fitted Log-Normal Model}}: $\\mu = {ln.get('mu', 0.0):.3f}$, $\\sigma = {ln.get('sigma', 0.0):.3f}$.
    \\item \\textbf{{Goodness-of-Fit}}: Kolmogorov-Smirnov test statistic $D_{{KS}} = {ln.get('ks_statistic', 0.0):.3f}$ ($p = {ln.get('p_value', 0.0):.3f}$).
    \\item \\textbf{{Model Selection}}: Evaluated model preferred: \\textit{{{fit_info.get('best_model', 'Log-Normal')}}}.
\\end{{itemize}}

\\section{{Process Survival Dynamics (Kaplan-Meier)}}
The non-parametric survival function $\\hat{{S}}(t)$ for user applications is defined by:
\\begin{{equation}}
\\hat{{S}}(t) = \\prod_{{t_i \\le t}} \\left( 1 - \\frac{{d_i}}{{n_i}} \\right)
\\end{{equation}}
Estimated median lifespan of active user processes: \\textbf{{{km_user.get('median_survival_seconds', 0.0) / 3600.0:.2f} hours}}.

\\section{{Stochastic Point Process Analysis (Kernel Journal)}}
System events inter-arrival times analysis:
\\begin{{itemize}}
    \\item Empirical Arrival Rate ($\\hat{{\\lambda}}$): \\textbf{{{point_res.get('lambda_rate_hz', 0.0):.2f} events/sec}}.
    \\item Coefficient of Variation ($CV = s / \\bar{{\\Delta t}}$): \\textbf{{{point_res.get('cv', 0.0):.2f}}} (Theoretical Poisson $CV = 1.00$).
    \\item Inferred Point Process Regime: \\textit{{{point_res.get('regime', 'N/A')}}}.
\\end{{itemize}}

\\section{{Temporal Drift and Memory Leak OLS Regression}}
Linear drift model: $y_t = \\beta_0 + \\beta_1 t + \\epsilon_t$.
\\begin{{itemize}}
    \\item Estimated Drift Slope ($\\hat{{\\beta}}_1$): \\textbf{{{reg_drift.get('slope', 0.0):.4f} MiB/sec}} ($p = {reg_drift.get('p_value', 1.0):.4f}$, $R^2 = {reg_drift.get('r2', 0.0):.3f}$).
    \\item Leak Diagnosis: \\textbf{{{reg_drift.get('leak_status', 'Ergodic')}}}.
\\end{{itemize}}

\\end{{document}}
"""
        with open(filepath, 'w') as f:
            f.write(tex)
        return True
    except Exception as e:
        print(f"Error exporting LaTeX report: {e}")
        return False


def export_csv_dataset(filepath: str, processes: List[Any]) -> bool:
    """Exports raw process snapshot as structured CSV for R, Julia, or Stata analysis."""
    try:
        with open(filepath, 'w', newline='') as f:
            writer = csv.writer(f)
            writer.writerow([
                "PID", "Name", "User", "Category", "CPU_Percent",
                "RSS_Memory_MiB", "VMS_Memory_MiB", "Num_Threads",
                "Status", "Age_Seconds", "Mod_Z_Score_RSS", "Outlier_Flag"
            ])
            for p in processes:
                writer.writerow([
                    p.pid, p.name, p.user, p.category, f"{p.cpu_pct:.2f}",
                    f"{p.rss_mb:.2f}", f"{p.vms_mb:.2f}", p.threads,
                    p.status, f"{p.age_seconds:.1f}", f"{p.mod_z_rss:.3f}",
                    "YES" if p.is_outlier else "NO"
                ])
        return True
    except Exception as e:
        print(f"Error exporting CSV: {e}")
        return False


def export_json_schema(filepath: str, data: Dict[str, Any]) -> bool:
    """Exports machine-readable JSON schema."""
    try:
        with open(filepath, 'w') as f:
            json.dump(data, f, indent=4)
        return True
    except Exception as e:
        print(f"Error exporting JSON: {e}")
        return False
